"""Host rule emission: one source, many hosts, no privileged editor."""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from agentloom_runtime.hostrules import load_manifest, render, status, sync

SOURCE_TEXT = "# Bootstrap\n\nRun `agentloom-session resume` first.\n"

HOSTRULES_PKG = Path(__file__).resolve().parents[1] / "src" / "agentloom_runtime" / "hostrules"


def _repo(tmp_path: Path, targets: list[dict]) -> Path:
    (tmp_path / "agents").mkdir()
    (tmp_path / "agents" / "BOOTSTRAP.md").write_text(SOURCE_TEXT, encoding="utf-8")
    (tmp_path / ".agentloom").mkdir()
    manifest = tmp_path / ".agentloom" / "hostrules.json"
    manifest.write_text(
        json.dumps({"source": "agents/BOOTSTRAP.md", "targets": targets}),
        encoding="utf-8",
    )
    return manifest


def test_one_source_reaches_every_host(tmp_path):
    manifest_path = _repo(
        tmp_path,
        [
            {"path": "AGENTS.md"},
            {"path": ".someeditor/rules/bootstrap.md"},
            {"path": "nested/deeply/INSTRUCTIONS.md"},
        ],
    )
    manifest = load_manifest(manifest_path, root=tmp_path)
    actions = sync(manifest)

    assert [a for _, a in actions] == ["created", "created", "created"]
    bodies = {
        t.path: (tmp_path / t.path).read_text(encoding="utf-8") for t in manifest.targets
    }
    for body in bodies.values():
        assert "Run `agentloom-session resume` first." in body
    # Same instruction everywhere, modulo the per-target header.
    assert len({b.split("-->")[-1] for b in bodies.values()}) == 1


def test_missing_parent_directories_are_created(tmp_path):
    manifest_path = _repo(tmp_path, [{"path": "a/b/c/rules.md"}])
    sync(load_manifest(manifest_path, root=tmp_path))
    assert (tmp_path / "a" / "b" / "c" / "rules.md").is_file()


def test_front_matter_is_emitted_when_a_host_needs_it(tmp_path):
    manifest_path = _repo(
        tmp_path,
        [
            {"path": "plain.md"},
            {
                "path": "fancy.mdc",
                "front_matter": {"alwaysApply": True, "description": "Session bootstrap"},
            },
        ],
    )
    manifest = load_manifest(manifest_path, root=tmp_path)
    sync(manifest)

    fancy = (tmp_path / "fancy.mdc").read_text(encoding="utf-8")
    assert fancy.startswith("---\nalwaysApply: true\n")
    assert '"Session bootstrap"' in fancy
    assert not (tmp_path / "plain.md").read_text(encoding="utf-8").startswith("---")


def test_edited_source_makes_targets_stale_then_syncs(tmp_path):
    manifest_path = _repo(tmp_path, [{"path": "AGENTS.md"}])
    manifest = load_manifest(manifest_path, root=tmp_path)
    sync(manifest)
    assert [s.state for s in status(manifest)] == ["ok"]

    (tmp_path / "agents" / "BOOTSTRAP.md").write_text("# Changed\n", encoding="utf-8")
    assert [s.state for s in status(manifest)] == ["stale"]

    sync(manifest)
    assert [s.state for s in status(manifest)] == ["ok"]
    assert "Changed" in (tmp_path / "AGENTS.md").read_text(encoding="utf-8")


def test_hand_edited_target_is_reported_stale(tmp_path):
    manifest_path = _repo(tmp_path, [{"path": "AGENTS.md"}])
    manifest = load_manifest(manifest_path, root=tmp_path)
    sync(manifest)
    (tmp_path / "AGENTS.md").write_text("hand edited\n", encoding="utf-8")
    assert [s.state for s in status(manifest)] == ["stale"]


def test_unwritten_target_is_reported_missing(tmp_path):
    manifest_path = _repo(tmp_path, [{"path": "AGENTS.md"}])
    manifest = load_manifest(manifest_path, root=tmp_path)
    assert [s.state for s in status(manifest)] == ["missing"]


def test_generated_files_say_not_to_edit_them(tmp_path):
    manifest_path = _repo(tmp_path, [{"path": "AGENTS.md"}])
    manifest = load_manifest(manifest_path, root=tmp_path)
    body = render(manifest, manifest.targets[0])
    assert "Generated by agentloom-hostrules" in body
    assert "agents/BOOTSTRAP.md" in body
    assert "source-sha256:" in body


def test_manifest_errors_are_explicit(tmp_path):
    (tmp_path / ".agentloom").mkdir()
    bad = tmp_path / ".agentloom" / "hostrules.json"

    bad.write_text(json.dumps({"targets": [{"path": "x.md"}]}), encoding="utf-8")
    with pytest.raises(ValueError, match="requires a 'source'"):
        load_manifest(bad, root=tmp_path)

    bad.write_text(json.dumps({"source": "agents/BOOTSTRAP.md"}), encoding="utf-8")
    with pytest.raises(ValueError, match="no targets"):
        load_manifest(bad, root=tmp_path)

    bad.write_text(
        json.dumps({"source": "nope.md", "targets": [{"path": "x.md"}]}), encoding="utf-8"
    )
    with pytest.raises(FileNotFoundError):
        load_manifest(bad, root=tmp_path)


def test_emitter_privileges_no_editor():
    """Adding a new IDE must be a manifest entry, never a code change.

    If an editor's name appears in the emitter, some host has become special and
    the next one will need a release to support.
    """
    editors = ("cursor", "cline", "windsurf", "copilot", "antigravity", "vscode", "claude")
    for path in HOSTRULES_PKG.glob("*.py"):
        lowered = path.read_text(encoding="utf-8").lower()
        for editor in editors:
            assert editor not in lowered, f"{path.name} hardcodes the host '{editor}'"
