"""Layer 0 working-session memory: cross-host, host-agnostic session continuity.

Where the curated-knowledge, management, and plan/provenance layers answer
"what does the organization know" and "what is the team doing", this layer
answers "where did this agent and this human leave off in this repository" —
and answers it from a shared database rather than from editor-local storage, so
the answer survives switching machines or IDEs.
"""

from agentloom_runtime.session.identity import (
    DEFAULT_LANE,
    HostContext,
    detect_host_context,
    detect_workspace_key,
    normalize_workspace_key,
    resolve_lane,
    resolve_operator_id,
)
from agentloom_runtime.session.readers import discover_transcripts, get_reader
from agentloom_runtime.session.store import (
    ArchiveHit,
    LanesUnavailableError,
    ResumePack,
    SessionInUseError,
    SessionOpenError,
    SessionRecord,
    TranscriptRecord,
    add_turn,
    checkpoint,
    close_session,
    compact_embeddings,
    get_session_lineage,
    get_workspace_session_tree,
    index_transcript,
    index_workspace,
    list_checkpoints,
    list_session_hosts,
    list_transcripts,
    live_hosts,
    load_transcript,
    open_session,
    park_session,
    touch_host,
    render_resume_pack,
    resume,
    search_archive,
    search_sessions,
    set_transcript_presentation,
    set_transcript_title,
    store_transcript,
)
from agentloom_runtime.session.transcript import (
    TranscriptDocument,
    redact,
    render_markdown,
    render_text,
)
from agentloom_runtime.session.vcs import VcsState, collect_vcs_state

__all__ = [
    "ArchiveHit",
    "DEFAULT_LANE",
    "HostContext",
    "LanesUnavailableError",
    "ResumePack",
    "SessionInUseError",
    "SessionOpenError",
    "SessionRecord",
    "TranscriptDocument",
    "TranscriptRecord",
    "VcsState",
    "add_turn",
    "checkpoint",
    "close_session",
    "compact_embeddings",
    "collect_vcs_state",
    "detect_host_context",
    "detect_workspace_key",
    "discover_transcripts",
    "get_reader",
    "get_session_lineage",
    "get_workspace_session_tree",
    "index_transcript",
    "index_workspace",
    "list_checkpoints",
    "list_session_hosts",
    "list_transcripts",
    "live_hosts",
    "load_transcript",
    "normalize_workspace_key",
    "open_session",
    "park_session",
    "redact",
    "render_markdown",
    "render_resume_pack",
    "render_text",
    "resolve_lane",
    "resolve_operator_id",
    "resume",
    "touch_host",
    "search_archive",
    "search_sessions",
    "set_transcript_presentation",
    "store_transcript",
]
