"""Distribute one canonical bootstrap instruction to every host's rule file.

Each AI coding host auto-loads a different file: one reads ``AGENTS.md``,
another a file under its own dot-directory, another something else entirely.
The instruction itself is identical in all of them, so it should be written once
and generated everywhere.

This module knows about **no specific IDE**. A target is a path plus optional
front matter; the path is the entire host binding. Supporting an editor that
does not exist yet is a one-line manifest entry, not a code change and not an
upstream release.

Manifest (JSON), conventionally ``.agentloom/hostrules.json``::

    {
      "source": "agents/AGENT_BOOTSTRAP.md",
      "targets": [
        {"path": "AGENTS.md"},
        {"path": ".some-editor/rules/agentloom-session.md",
         "front_matter": {"alwaysApply": true, "description": "..."}}
      ]
    }
"""

from __future__ import annotations

import hashlib
import json
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Optional

__all__ = [
    "Manifest",
    "Target",
    "TargetStatus",
    "load_manifest",
    "render",
    "status",
    "sync",
]

GENERATED_MARKER = "agentloom-hostrules"
DEFAULT_MANIFEST = Path(".agentloom") / "hostrules.json"


@dataclass(frozen=True)
class Target:
    path: str
    front_matter: Optional[dict[str, Any]] = None
    note: Optional[str] = None


@dataclass(frozen=True)
class Manifest:
    root: Path
    source: str
    targets: tuple[Target, ...]

    @property
    def source_path(self) -> Path:
        return self.root / self.source


@dataclass(frozen=True)
class TargetStatus:
    target: Target
    exists: bool
    current: bool

    @property
    def state(self) -> str:
        if not self.exists:
            return "missing"
        return "ok" if self.current else "stale"


def load_manifest(path: Path, root: Optional[Path] = None) -> Manifest:
    data = json.loads(path.read_text(encoding="utf-8"))
    source = data.get("source")
    if not source:
        raise ValueError(f"{path}: manifest requires a 'source' path")

    raw_targets = data.get("targets") or []
    if not raw_targets:
        raise ValueError(f"{path}: manifest lists no targets")

    targets = []
    for entry in raw_targets:
        if not entry.get("path"):
            raise ValueError(f"{path}: every target requires a 'path'")
        targets.append(
            Target(
                path=entry["path"],
                front_matter=entry.get("front_matter"),
                note=entry.get("note"),
            )
        )

    manifest_root = root or path.parent.parent
    manifest = Manifest(root=manifest_root, source=source, targets=tuple(targets))
    if not manifest.source_path.is_file():
        raise FileNotFoundError(f"source not found: {manifest.source_path}")
    return manifest


def _source_digest(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()[:16]


def _format_front_matter(values: dict[str, Any]) -> list[str]:
    """Emit flat YAML front matter.

    Deliberately minimal: host rule files use scalar keys, and depending on a
    YAML library for that would be a heavier contract than the format needs.
    """
    lines = ["---"]
    for key, value in values.items():
        if isinstance(value, bool):
            rendered = "true" if value else "false"
        elif isinstance(value, (int, float)):
            rendered = str(value)
        elif isinstance(value, list):
            rendered = "[" + ", ".join(json.dumps(str(v)) for v in value) + "]"
        else:
            rendered = json.dumps(str(value))
        lines.append(f"{key}: {rendered}")
    lines.append("---")
    return lines


def render(manifest: Manifest, target: Target) -> str:
    """Render the file content for one target."""
    source_text = manifest.source_path.read_text(encoding="utf-8")
    digest = _source_digest(source_text)

    parts: list[str] = []
    if target.front_matter:
        parts.extend(_format_front_matter(target.front_matter))
        parts.append("")
    parts.append(f"<!-- Generated by {GENERATED_MARKER} from {manifest.source}. -->")
    parts.append(f"<!-- Edit that file, then re-run sync. source-sha256: {digest} -->")
    parts.append("")
    parts.append(source_text.strip())
    parts.append("")
    return "\n".join(parts)


def status(manifest: Manifest) -> list[TargetStatus]:
    results = []
    for target in manifest.targets:
        path = manifest.root / target.path
        if not path.is_file():
            results.append(TargetStatus(target, exists=False, current=False))
            continue
        current = path.read_text(encoding="utf-8") == render(manifest, target)
        results.append(TargetStatus(target, exists=True, current=current))
    return results


def sync(manifest: Manifest) -> list[tuple[Target, str]]:
    """Write every out-of-date target. Returns (target, action) pairs."""
    actions = []
    for entry in status(manifest):
        path = manifest.root / entry.target.path
        if entry.current:
            actions.append((entry.target, "unchanged"))
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(render(manifest, entry.target), encoding="utf-8")
        actions.append((entry.target, "created" if not entry.exists else "updated"))
    return actions
